site_name: Configure with confidence 😎

docs_dir: .
site_dir: ../site
repo_url: https://github.com/NetherlandsForensicInstitute/confidence/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 2
          show_root_heading: true
          show_source: false
          show_bases: false
          docstring_style: sphinx
          separate_signature: true
          signature_crossrefs: true

nav:
  - Home:
    - index.md
    - Changelog: changelog.md
  - Usage:
    - usage/loading.md
    - usage/runtime.md
    - usage/advanced.md
  - Reference:
    - reference/loading.md
    - reference/objects.md
    - reference/manipulation.md
    - reference/exceptions.md
